spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pos
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/test?authSource=admin
      username: user
      password: password
      database: pos

# JWT Config
SECRET_KEY: qQj8bBOdMLKamuJEfcJ7wiBbPAQ7+8d8nP/V5XWN5zdSD67Yp7KwT9Y/QouShM+9
# access token is valid for 1 day
EXPIRATION_TIME: 86400000
# refresh token is valid for 7 days
REFRESH_EXPIRATION_TIME: 604800000