version: '3'

services:
  pos:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pos
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/pos/mysql
    ports:
      - "3306:3306"

volumes:
  data:
