version: '3'

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pos
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/pos/mysql
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: pos
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  data:
  mongodb_data_container:
